/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airline_reservation;

import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author LENOVO
 */
public class Cancellation extends javax.swing.JFrame {

    /**
     * Creates new form Cancellation
     */
    public Cancellation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        to = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        passport = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        from = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        to.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.focusedBackground"));
        to.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 3, 48)); // NOI18N
        jLabel1.setText("                      CANCELLATION");
        to.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 20, 870, 70));

        jLabel2.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel2.setText("Email");
        to.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 117, 60, 30));
        to.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 210, 30));

        jLabel3.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel3.setText("Firstname");
        to.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 117, 80, 30));
        to.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 200, 30));

        jLabel4.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel4.setText("Last Name");
        to.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, 30));

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        to.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 210, 30));

        jLabel5.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel5.setText("Contact");
        to.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 70, 30));
        to.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 200, 30));

        jLabel6.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel6.setText("Passport No.");
        to.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 30));

        passport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passportActionPerformed(evt);
            }
        });
        to.add(passport, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 220, 30));

        jLabel7.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel7.setText("From");
        to.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 60, 30));
        to.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 210, 30));

        jLabel8.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jLabel8.setText("To");
        to.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 50, 30));
        to.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 220, 30));

        cancel.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        to.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 100, 30));

        jButton1.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        to.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 110, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airline_reservation/30.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        to.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-420, 0, 1180, 750));

        getContentPane().add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 760, 460));

        setBounds(0, 0, 732, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void passportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passportActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        
       /* try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        java.sql.Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sign", "root", "Ash@9766");

        // Corrected SQL query for deletion
        String sql1 = "DELETE FROM customer WHERE `firstname` = ? AND `lastname` = ? AND `passport` = ?";
        //String sql2 ="DELETE FROM fB WHERE 'pass' =?";
         //PreparedStatement pst1 = c.prepareStatement(sql2);
        PreparedStatement pst = c.prepareStatement(sql1);
        pst.setString(1, fname.getText());
        pst.setString(2, lname.getText());
        pst.setString(3, passport.getText());
        //pst1.setString(3, passport.getText());

        int rowsAffected = pst.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Ticket Cancelled Successfully");
        } else {
            JOptionPane.showMessageDialog(this, "Cancellation Failed");
        }

        c.close();
    } catch (HeadlessException | SQLException e) {
        System.out.println(e.getMessage());
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(newCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
   */
       try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        java.sql.Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/sign", "root", "Ash@9766");

        // SQL query for deletion in the fb table
        String sql2 = "DELETE FROM fb WHERE `pass` = ?";
        PreparedStatement pst2 = c.prepareStatement(sql2);
        pst2.setString(1, passport.getText());
        int rowsAffectedFB = pst2.executeUpdate();

        // SQL query for deletion in the customer table
        String sql1 = "DELETE FROM customer WHERE `passport` = ?";
        PreparedStatement pst1 = c.prepareStatement(sql1);
        pst1.setString(1, passport.getText());
        int rowsAffectedCustomer = pst1.executeUpdate();

        if (rowsAffectedCustomer > 0 || rowsAffectedFB > 0) {
            JOptionPane.showMessageDialog(this, "Ticket Cancelled Successfully");
        } else {
            JOptionPane.showMessageDialog(this, "Cancellation Failed. No matching records found.");
        }

        c.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "SQL Error: " + e.getMessage());
    } catch (ClassNotFoundException ex) {
        JOptionPane.showMessageDialog(this, "Class Not Found Error: " + ex.getMessage());
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_cancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);  //login page false;
            main m=new main();
            m.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancellation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField from;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField passport;
    private javax.swing.JPanel to;
    // End of variables declaration//GEN-END:variables
}
